use std::ffi::{c_char, c_int, CStr, CString};
use std::sync::Mutex;

/// Session mode: Hold (long press) or Toggle (tap)
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SPSessionMode {
    Hold = 0,
    Toggle = 1,
}

/// Context passed when beginning a session
#[repr(C)]
pub struct SPSessionContext {
    pub mode: SPSessionMode,
    /// Frontmost app bundle ID (UTF-8 C string, nullable)
    pub frontmost_bundle_id: *const c_char,
    /// Frontmost app PID
    pub frontmost_pid: c_int,
    /// Monotonic session token generated by the ObjC caller.
    /// Passed back through all session callbacks so the caller can
    /// discard events from superseded sessions.
    pub session_token: u64,
}

/// Callback function types that Obj-C registers with Rust.
/// Session-scoped callbacks carry a `token` that the caller can compare
/// against its current session token to discard stale events.
#[repr(C)]
pub struct SPCallbacks {
    /// Called when a session is ready (recording can begin)
    pub on_session_ready: Option<extern "C" fn(token: u64)>,
    /// Called when a session encounters an error
    /// message is a UTF-8 C string, caller must NOT free it
    pub on_session_error: Option<extern "C" fn(token: u64, message: *const c_char)>,
    /// Called for non-fatal warnings that should be shown to the user
    /// message is a UTF-8 C string, caller must NOT free it
    pub on_session_warning: Option<extern "C" fn(token: u64, message: *const c_char)>,
    /// Called when the final corrected text is ready
    /// text is a UTF-8 C string, caller must NOT free it
    pub on_final_text_ready: Option<extern "C" fn(token: u64, text: *const c_char)>,
    /// Called for log events (not session-scoped, no token)
    /// level: 0=error, 1=warn, 2=info, 3=debug
    pub on_log_event: Option<extern "C" fn(level: c_int, message: *const c_char)>,
    /// Called when session state changes (for status bar updates)
    /// state is a UTF-8 C string representing the state name
    pub on_state_changed: Option<extern "C" fn(token: u64, state: *const c_char)>,
    /// Called when an interim (partial) ASR result arrives during recording
    /// text is a UTF-8 C string, caller must NOT free it
    pub on_interim_text: Option<extern "C" fn(token: u64, text: *const c_char)>,
    /// Called when ASR finalization completes with the final recognized text,
    /// before LLM correction begins. Used to display ASR result in the overlay.
    pub on_asr_final_text: Option<extern "C" fn(token: u64, text: *const c_char)>,
    /// Called when a rewrite (using an alternative prompt template) completes.
    /// text is a UTF-8 C string, caller must NOT free it.
    pub on_rewrite_text_ready: Option<extern "C" fn(token: u64, text: *const c_char)>,
    /// Called just before `on_final_text_ready` with session result metadata
    /// for history recording. Strings are UTF-8 C strings, caller must NOT
    /// free them. `llm_applied` is true only when LLM correction ran and its
    /// output was used (false when the LLM is disabled, fails, or its output
    /// is discarded as degenerate).
    pub on_session_result_meta: Option<
        extern "C" fn(
            token: u64,
            asr_text: *const c_char,
            asr_provider: *const c_char,
            llm_applied: bool,
        ),
    >,
}

static CALLBACKS: Mutex<Option<SPCallbacks>> = Mutex::new(None);

/// Build a C string for FFI, stripping any interior NUL bytes (which would
/// otherwise cause CString::new to fail and silently drop the whole string).
fn ffi_cstring(s: &str) -> CString {
    match CString::new(s) {
        Ok(c) => c,
        Err(_) => CString::new(s.replace('\0', "")).unwrap_or_default(),
    }
}

pub fn register_callbacks(callbacks: SPCallbacks) {
    let mut cb = CALLBACKS.lock().unwrap();
    *cb = Some(callbacks);
}

pub fn invoke_session_ready(token: u64) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_session_ready)
    };
    if let Some(f) = f {
        f(token);
    }
}

pub fn invoke_session_error(token: u64, message: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_session_error)
    };
    if let Some(f) = f {
        let c_msg = ffi_cstring(message);
        f(token, c_msg.as_ptr());
    }
}

pub fn invoke_session_warning(token: u64, message: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_session_warning)
    };
    if let Some(f) = f {
        let c_msg = ffi_cstring(message);
        f(token, c_msg.as_ptr());
    }
}

pub fn invoke_final_text_ready(token: u64, text: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_final_text_ready)
    };
    if let Some(f) = f {
        let c_text = ffi_cstring(text);
        f(token, c_text.as_ptr());
    }
}

pub fn invoke_log_event(level: i32, message: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_log_event)
    };
    if let Some(f) = f {
        let c_msg = ffi_cstring(message);
        f(level as c_int, c_msg.as_ptr());
    }
}

pub fn invoke_state_changed(token: u64, state: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_state_changed)
    };
    if let Some(f) = f {
        let c_state = ffi_cstring(state);
        f(token, c_state.as_ptr());
    }
}

pub fn invoke_interim_text(token: u64, text: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_interim_text)
    };
    if let Some(f) = f {
        let c_text = ffi_cstring(text);
        f(token, c_text.as_ptr());
    }
}

pub fn invoke_asr_final_text(token: u64, text: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_asr_final_text)
    };
    if let Some(f) = f {
        let c_text = ffi_cstring(text);
        f(token, c_text.as_ptr());
    }
}

pub fn invoke_session_result_meta(
    token: u64,
    asr_text: &str,
    asr_provider: &str,
    llm_applied: bool,
) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_session_result_meta)
    };
    if let Some(f) = f {
        let c_asr_text = ffi_cstring(asr_text);
        let c_provider = ffi_cstring(asr_provider);
        f(token, c_asr_text.as_ptr(), c_provider.as_ptr(), llm_applied);
    }
}

pub fn invoke_rewrite_text_ready(token: u64, text: &str) {
    let f = {
        let cb = CALLBACKS.lock().unwrap();
        cb.as_ref().and_then(|cbs| cbs.on_rewrite_text_ready)
    };
    if let Some(f) = f {
        let c_text = ffi_cstring(text);
        f(token, c_text.as_ptr());
    }
}

/// Feedback configuration exposed to the Obj-C layer
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SPFeedbackConfig {
    pub start_sound: bool,
    pub stop_sound: bool,
    pub error_sound: bool,
    pub mute_system_output: bool,
}

/// Clipboard configuration exposed to the Obj-C layer
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SPClipboardConfig {
    /// Delay (ms) between the automatic-paste completion callback and
    /// clipboard restoration. Validated to 0..=60000 at config load.
    pub restore_delay_ms: u32,
}

/// Hotkey configuration exposed to the Obj-C layer
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SPHotkeyConfig {
    /// Trigger hotkey primary key code (e.g. 63 for Fn, 58 for Left Option)
    pub trigger_key_code: u16,
    /// Trigger hotkey alternative key code (e.g. 179 for Globe key), 0 if none
    pub trigger_alt_key_code: u16,
    /// Trigger hotkey modifier flag. For modifier-only hotkeys this is the
    /// observed key-state flag; for keyDown hotkeys this is the required
    /// generic modifier mask.
    pub trigger_modifier_flag: u64,
    /// Trigger hotkey match kind: 0 = modifier-only, 1 = keyDown/keyUp.
    pub trigger_match_kind: u8,
    /// Trigger mode: 0 = hold, 1 = toggle, 2 = double-tap start/single-tap stop
    pub trigger_mode: u8,
}

/// Helper to convert a C string pointer to a Rust &str
///
/// # Safety
/// The pointer must be valid and null-terminated UTF-8.
pub unsafe fn cstr_to_str<'a>(ptr: *const c_char) -> Option<&'a str> {
    if ptr.is_null() {
        return None;
    }
    unsafe { CStr::from_ptr(ptr) }.to_str().ok()
}
